steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/myfirstproject", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/myfirstproject"]
  - name: "gcr.io/cloud-builders/gcloud"
  entrypoint: /bin/sh
  args:
  - "-c"
  - |
    sed -i "s/\\$PROJECT_ID/$PROJECT_ID/g" gke.yaml
  # deploy container image to GKE
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/myfirstproject
  - --location=us-central1-c
  - --cluster=cluster-1
  - --namespace=gcp-devops-prod
options:
  logging: CLOUD_LOGGING_ONLY
